version: "3.4"
services:
  worker:
    container_name: worker
    image: gitlab.diva-e.com:5000/fynn.fischbach/onlineshop-backend:latest
    ports:
      - 8085:8085
  frontend:
    image: gitlab.diva-e.com:5000/fynn.fischbach/onlineshop:latest
    ports:
      - 3000:3000
    depends_on:
      - worker
